### PR TITLE
Update to 1.13

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by mdjarv — COMMENTED** [review]
Following the MSDN coding conventions, indent with 4 spaces instead of tabs:

https://msdn.microsoft.com/en-us/library/ff926074.aspx#Anchor_1

- "smart indenting, four-character indents, tabs saved as spaces"

**Comment by mdjarv** [comment]
Changed from tabs to 2 spaces, I'd like indents to be 4 spaces like the MSDN conventions specify :)

**Comment by mdjarv** [comment]
Merging anyway to not keep this change hanging, but it could be a good idea to check your editor settings to match the MSDN recommendations

**Comment by ghost** [comment]
Sorry, i think 2 spaces is enought. Also Visual Studio and Xamarin only uses 2 spaces for indenting. Microsoft is a master in not keep their own standards... so why we should do it not like all other programmers do and use 2 spaces for indenting??

**Pull request merged**
